# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ma-zmq"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Fernando Alonso"]
  s.date = "2012-08-15"
  s.description = "RoundRobin handler for ZMQ over EventedMachine"
  s.email = "krakatoa1987@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".simplecov",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "benchmark/bench.rb",
    "benchmark/results.txt",
    "lib/ma-zmq.rb",
    "lib/ma-zmq/connection_handler.rb",
    "lib/ma-zmq/proxy.rb",
    "lib/ma-zmq/proxy/backend.rb",
    "lib/ma-zmq/proxy/balancer.rb",
    "lib/ma-zmq/pull.rb",
    "lib/ma-zmq/push.rb",
    "lib/ma-zmq/reply.rb",
    "lib/ma-zmq/request.rb",
    "lib/ma-zmq/socket_handler.rb",
    "ma-zmq.gemspec",
    "spec/reply_spec.rb",
    "spec/request_spec.rb",
    "spec/socket_handler_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/al-nattahnam/ma-zmq"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "RoundRobin handler for ZMQ over EventedMachine"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, ["= 1.0.0.beta.4"])
      s.add_runtime_dependency(%q<ffi-rzmq>, ["= 0.9.3"])
      s.add_development_dependency(%q<rspec>, ["~> 2.11.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<eventmachine>, ["= 1.0.0.beta.4"])
      s.add_dependency(%q<ffi-rzmq>, ["= 0.9.3"])
      s.add_dependency(%q<rspec>, ["~> 2.11.0"])
      s.add_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<eventmachine>, ["= 1.0.0.beta.4"])
    s.add_dependency(%q<ffi-rzmq>, ["= 0.9.3"])
    s.add_dependency(%q<rspec>, ["~> 2.11.0"])
    s.add_dependency(%q<bundler>, ["~> 1.1.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

